### ISSUE TITLE
"Initialising..." with no end...

### ISSUE THREAD

**Issue by Benjiiben53** [Osiris-Team/AutoPlug-Plugin#6]
/!\ I'm not good in English, sorry in advance /!\

Hello, i have a little probleme with a spigot server, when i setup all settings of AutoPlug and i start it for the second time, i enter the key as indicated here: https://www.spigotmc.org/resources/autoplug-automatic-plugin-updater.78414/ but when Initialising Self-updater etc... it getting stuck here. AutoPlug working with BungeeCord on 25565 but not on my spigot server on 25566 what i have missed ? Here is a console screen:
![tempsnip](https://user-images.githubusercontent.com/38442738/120070440-db2b4d00-c08a-11eb-8462-485a761adec5.png)

Thank you in advance for answers that will solve (or not) my problem. On these word, have a nice day !

**Comment by Osiris-Team** [comment]
Could be solved, but its weird that the error message wasn't shown.
Gonna take a look at that.

**Comment by Benjiiben53** [comment]
FIX: Duplicate plugins stop AutoPlug when Initialising... check if you didn't have a duplicated plugins
