### ISSUE TITLE
sending commands to wrong server

### ISSUE THREAD

**Issue by werken23** [Osiris-Team/AutoPlug-Plugin#8]
when using "/.stop", "/.restart" or "/.stop both" on a server it executes the command on a different server in the network. (the one with the lowest port)

**Comment by Osiris-Team** [comment]
That shouldn't work since autoplug compares the server keys and only connects to it if it is the same key...

**Comment by werken23** [comment]
Maybe something to do with all servers having "NO_KEY"?

**Comment by Osiris-Team** [comment]
Uh that would make more sense. yup
Gonna fix it asap.

**Comment by Osiris-Team** [comment]
should be fixed in 1.1
